# Generated by Django 4.2.20 on 2025-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demonym",
                    models.CharField(
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]

