# Generated by Django 4.2.20 on 2025-03-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nationality",
            options={"ordering": ["demonym"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demonym",
                    models.CharField(max_length=255),
                ),
                (
                    "country",
                    models.CharField(max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            options={"ordering": ["id"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=6),
                ),
                (
                    "forename",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "surname",
                    models.CharField(max_length=255),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True),
                ),
                (
                    "url",
                    models.URLField(blank=True),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.nationality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Constructor",
            options={"ordering": ["id"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "name",
                    models.CharField(max_length=255),
                ),
                (
                    "url",
                    models.URLField(blank=True),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.nationality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Circuit",
            options={"ordering": ["id"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "name",
                    models.CharField(max_length=255),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.nationality",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, max_digits=32, decimal_places=16),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, max_digits=32, decimal_places=16),
                ),
                (
                    "altitude",
                    models.IntegerField(blank=True, help_text="Measured in meters"),
                ),
                (
                    "url",
                    models.URLField(blank=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            options={"ordering": ["-date_of_race"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255),
                ),
                (
                    "date_of_race",
                    models.DateTimeField(),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(),
                ),
                (
                    "url",
                    models.URLField(blank=True),
                ),
                (
                    "circuit",
                    models.ForeignKey(
                        to="app.circuit",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Qualifying",
            options={"ordering": ["id"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(),
                ),
                (
                    "q_one",
                    models.DurationField(blank=True, null=True),
                ),
                (
                    "q_two",
                    models.DurationField(blank=True, null=True),
                ),
                (
                    "q_three",
                    models.DurationField(blank=True, null=True),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        to="app.constructor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        to="app.driver",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        to="app.race",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="quali",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LapTime",
            options={"ordering": ["-race"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lap_number",
                    models.PositiveIntegerField(),
                ),
                (
                    "position",
                     models.PositiveIntegerField(),
                ),
                (
                    "time",
                    models.DurationField(blank=True, null=True),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lap_times",
                        to="app.race",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PitStop",
            options={"ordering": ["id"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_number",
                    models.PositiveIntegerField(),
                ),
                (
                    "lap_number",
                    models.PositiveIntegerField(),
                ),
                (
                    "local_time",
                    models.TimeField(),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pit_stops",
                        to="app.race",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DropStuff",
            options={"ordering": ["id"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.BinaryField(blank=True, editable=True),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255),
                ),
            ],
        ),
    ]

