# Generated by Django 4.2.20 on 2025-03-17 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.CharField(blank=True, max_length=255)),
                ("number", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(blank=True, max_length=6)),
                ("forename", models.CharField(blank=True, max_length=255)),
                ("surname", models.CharField(blank=True, max_length=255)),
                ("date_of_birth", models.DateField(blank=True)),
                ("url", models.URLField()),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.nationality",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]

