# Generated by Django 5.2 on 2025-06-29 21:41

from django.db import migrations
from django.db import models
from django.utils import timezone


def mark_old_countries_as_deleted_at(apps, schema_editor):
    Nationality = apps.get_model('app', 'Nationality')
    nationality_objs = Nationality.objects.all()
    for n in nationality_objs:
        n.deleted_at = timezone.now()
    Nationality.objects.bulk_update(nationality_objs, ['deleted_at'])

def assign_drivers_to_new_country_values(apps, schema_editor):
    # Models that we're working with
    Nationality = apps.get_model("app", "Nationality")
    Driver = apps.get_model("app", "Driver")

    set_nationality = Nationality.objects.order_by('country').distinct('country')

    # Create all the new ones (unique)
    Nationality.objects.bulk_create([Nationality(country=i.country, demonym=i.demonym) for i in set_nationality])
    uni_n = Nationality.objects.filter(deleted_at__isnull=True)

    # Assign drivers to the new unique countries 'uni_n'
    driver_objs = Driver.objects.all()
    for d in driver_objs:
        d.nationality = uni_n.get(country=d.nationality.country)
    Driver.objects.bulk_update(driver_objs, ['nationality'])


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_insert_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="Nationality",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=mark_old_countries_as_deleted_at,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
        migrations.RunPython(
            code=assign_drivers_to_new_country_values,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
    ]

