# Generated by Django 5.2 on 2025-06-29 21:41

from django.db import migrations


def normalize_nationality(apps, schema_editor):
    Nationality = apps.get_model("app", "Nationality")
    Driver = apps.get_model("app", "Driver")
    drivers = Driver.objects.all()

    # Get the last object
    last_country = Nationality.objects.last()

    set_nationality = (
        Nationality
        .objects
        .filter(country__isnull=False)
        .order_by('country')
        .distinct('country')
    )
    # Create all the new ones (unique)
    Nationality.objects.bulk_create([Nationality(country=i.country, demonym=i.demonym) for i in set_nationality])

    uni_set = Nationality.objects.order_by("id")[2143:]
    for driver in drivers:
        new_country = uni_set.get(country=driver.nationality)
        driver.nationality = new_country
        driver.save()

    breakpoint()
    old_set = Nationality.objects.order_by("id")[:2142]
    old_set.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_insert_data"),
    ]

    operations = [
        migrations.RunPython(
            code=normalize_nationality,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
    ]

